module.exports = {
    http: {
        invalid_token: "The access token provided is expired, revoked, malformed, or invalid for other reasons.",
        invalid_apikey: "The provided APIKEY is malformed or invalid.",
        unverified_email: "Email address of the user has not been verified yet.",
        invalid_credentials: "Invalid Credentials",
        unauthorized_access: "You are not authorized to access this resource.",
        unauthorized_application: "You are not authorized to use this application.",
    },
    VERSION_SUCCESSFULLY_FETCHED: "The version has been successfully fetched.",
    DATABASE_ERROR: "Database error",
    ERROR_CODE_FIELD_UNIQUE: 'E_EMAIL_UNIQUE',
    RESOURCE_SUCCESSFULLY_CREATED: "The resource has been successfully created.",
    RESOURCE_SUCCESSFULLY_UPDATED: "The resource has been successfully updated.",
    RESOURCE_SUCCESSFULLY_DELETED: "The resource has been successfully deleted.",
    USER_SUCCESSFULLY_SIGNUP: "The user has been successfully signed up.",
    USER_SUCCESSFULLY_CONFIRMED: "The user has been successfully confirmed.",
    RESOURCE_NOT_FOUND: "The resource has not been found on the server.",
    RESOURCE_SUCCESSFULLY_FETCHED: "The resource has been successfully fetched.",
    INVALID_TOKEN: "Invalid Token",
    EXPIRED_TOKEN: "Expired Token",
    VALID_TOKEN: "Token is valid",
    TASK_SUCCESSFULLY_UPDATED: "The task has been successfully updated.",
    TASK_SUCCESSFULLY_CREATED: "The task has been successfully created.",
    TASKS_SUCCESSFULLY_FETCHED: "Tasks have been successfully fetched.",
    TASK_SUCCESSFULLY_DELETED: "The task has been successfully deleted."
};
